### ISSUE TITLE
Opening sidebar changes the width

### ISSUE THREAD

**Issue by Keith94** [MatthewBaa/Display_Page_Resolution#1]
By default the add-on displays the window resolution as `1268x855`. If you open a sidebar (Ctrl+B), the resolution changes to `1052x855`. Shouldn't the values stay the same?

**Comment by MatthewBaa** [comment]
This is intended. 

The add-on displays the resolution of the page, and the sidebar - similar to the developer tools - takes up a portion of the page's width.

Unfortunately the name of the add-on may be misleading, as it displays the page resolution instead of the entire Firefox window resolution. I'll change that asap.

I'll look to releasing an add-on which displays the window resolution instead of the page resolution, or push an update to include it in this add-on.

Thanks!

**Comment by Keith94** [comment]
Thanks, window resolution would be nice to have as an option or separate add-on.
